#!/bin/bash

sleep 0.5
xdotool key --clearmodifiers "ctrl+l"
sleep 0.25
xdotool key --clearmodifiers "ctrl+c"
sleep 0.25
URL=$(xclip -selection clipboard -o)
FILE="$(echo "$URL" | sed "s/file:\/\///g")"
if [ "$(bltn -lu | grep "$URL")" = "" ] && [ ! -f "$FILE" ] ; then
	notify-send -t 5000 "$URL was not saved."
else
	notify-send -t 5000 "$URL removed."
	bltn -d "$URL"
fi
