#!/bin/bash

sleep 0.5
xdotool key --clearmodifiers "ctrl+l"
sleep 0.25
xdotool key --clearmodifiers "ctrl+c"
sleep 0.25
URL=$(xclip -selection clipboard -o)
notify-send -t 5000 "$URL saved."
bltn -av "$URL"

