#!/bin/bash

CONFIGFILE="/home/$USER/.config/ril/ril.conf"

if [ ! -f "$CONFIGFILE" ] ; then
	mkdir -p "$(dirname "$CONFIGFILE")"
	echo 'SYNCDIR="/home/$USER/Articles/"'      >> "$CONFIGFILE"
	echo 'LOCALDIR="/home/$USER/.ReadItLater/"' >> "$CONFIGFILE"
	echo 'BROWSERCOMMAND=firefox'               >> "$CONFIGFILE"
	echo '#BROWSERCOMMAND=chromium-browser'     >> "$CONFIGFILE"
	echo Config file $CONFIGFILE created.
	echo You can now edit it to change variables.
	echo See README.md for more informations about variables.
	exit 0
fi

. "$CONFIGFILE"

SYNCARTICLESDIR="${SYNCDIR}/articles/"
LOCALARTICLESDIR="${LOCALDIR}/articles/"
SYNCVIDEOSDIR="${SYNCDIR}/videos/"
LOCALVIDEOSDIR="${LOCALDIR}/videos/"

create_dir () {
	if [ ! -d "$1" ] ; then
		mkdir -p "$1"
	fi
}

create_dir "$SYNCARTICLESDIR"
create_dir "$LOCALARTICLESDIR"
create_dir "$SYNCVIDEOSDIR"
create_dir "$LOCALVIDEOSDIR"

get_title () {
	GROSSTITLE="$(wget --quiet -O - "$1" | sed -n -e 'H;${x;s!.*<head[^>]*>\(.*\)</head>.*!\1!;tnext};b;:next;s!.*<title>\(.*\)</title>.*!\1!p')"
	echo '<HTML><BODY>'"$GROSSTITLE"'</BODY></HTML>' > /tmp/title.html
	w3m -dump /tmp/title.html
	rm /tmp/title.html
}

add () {
	case "$1" in
		"--article")
			DIRECTORY="$SYNCARTICLESDIR"
			;;
		"--video")
			DIRECTORY="$SYNCVIDEOSDIR"
			;;
	esac
	cd "$DIRECTORY"
	FILENAME=$(echo "$2" | sed "s/\/\//%/g" | cut -d% -f2 | sed "s/\//__/g")
	echo "$2" > "$FILENAME"
}

open_element () {
	case "$1" in
		"--article")
			if [ ! "$(ls | grep html$)" = "" ] ; then
				$BROWSERCOMMAND *.html
			fi
			if [ ! "$(ls | grep htm$)" = "" ] ; then
				$BROWSERCOMMAND *.htm
			fi
			;;
		"--video")
			vlc *
			;;
	esac
}

open () {
	case "$1" in
		"--article")
			DIRECTORY="$LOCALARTICLESDIR"
			;;
		"--video")
			DIRECTORY="$LOCALVIDEOSDIR"
			;;
	esac

	echo dir : $DIRECTORY
	cd "$DIRECTORY"
	K=1
	for I in $(ls -tr) ; do
		echo "$K" \| "$(cat "$I"/title.txt)"
		I="$(echo "$I" | sed "s/__/\//g")"
		echo \> "$I"
		echo ==============================================
		K=$(( $K+1 ))
	done

	echo Enter the number of the article you want to read:
	read NUMBER

	K=1
	for I in $(ls -tr) ; do
		if [ "$K" -eq "$NUMBER" ] ; then
			cd "$I"
			open_element "$1"
			cd ..
		fi
		K=$(( $K+1 ))
	done
}

remove () {
	case "$1" in
		"--article")
			SYNCDIRECTORY="$SYNCARTICLESDIR"
			LOCALDIRECTORY="$LOCALARTICLESDIR"
			;;
		"--video")
			SYNCDIRECTORY="$SYNCVIDEOSDIR"
			LOCALDIRECTORY="$LOCALVIDEOSDIR"
			;;
	esac
	cd "$SYNCDIRECTORY"
	if [ ! "$(ls)" = "" ] ; then
		K=1
		for ARTICLE in $(ls -tr) ; do
			TITLEFILE="${LOCALDIRECTORY}/${ARTICLE}/title.txt"
			if [ -f "$TITLEFILE" ] ; then
				echo "$K" \| "$(cat "$TITLEFILE")"
				echo \> "$(cat "$ARTICLE")"
			else
				echo "$K" \| $(cat "$ARTICLE")
			fi
			echo ========================================
			K=$(( $K+1 ))
		done
		case "$2" in
			"--articlesdir")
				echo "Enter the number(s) of the article(s) you want to remove (ex: 1 2 4):"
				;;
			"--storedir")
				echo "Enter the number(s) of the article(s) you want to re-download (ex: 1 2 4):"
				;;
		esac

		read NUMBER

		K=1
		for ARTICLE in $(ls -tr) ; do
			if [ "$(grep " $K " <<< " $NUMBER " )" ] ; then
				case "$2" in
					"--articlesdir")
						rm "$ARTICLE"
						;;
					"--storedir")
						rm -r "$LOCALDIRECTORY"/"$ARTICLE"
						;;
				esac
			fi
			K=$(( $K+1 ))
		done
	else
		echo No article saved
	fi
}

remove_dir () {
	cd "$1"
	rm -r *
}

list () {
	cd "$SYNCARTICLESDIR"
	if [ ! "$(ls)" = "" ] ; then
		for ARTICLE in $(ls -tr) ; do
			cat "$ARTICLE"
		done
	else
		echo No article saved
	fi
}

download () {
	case "$1" in
		"--articles")
			SYNCDIRECTORY="$SYNCARTICLESDIR"
			LOCALDIRECTORY="$LOCALARTICLESDIR"
			DOWNLOADCOMMAND='wget -nd -E -H -K -k -p -q '
			;;
		"--videos")
			SYNCDIRECTORY="$SYNCVIDEOSDIR"
			LOCALDIRECTORY="$LOCALVIDEOSDIR"
			DOWNLOADCOMMAND='youtube-dl'
			;;
	esac
	cd "$SYNCDIRECTORY"
	if [ ! "$(ls)" = "" ] ; then
		for FILE in * ; do
			cd "$LOCALDIRECTORY"
			if [ ! -d "$FILE" ] ; then
				mkdir "$FILE"
				cd "$FILE"
				LINK="$(cat "$SYNCDIRECTORY"/"$FILE")"
				echo Download "$LINK"
				$DOWNLOADCOMMAND "$LINK"
				echo "$(get_title "$LINK")" > title.txt
			fi
		done
	fi
}

clean () {
	case "$1" in
		"--articles")
			SYNCDIRECTORY="$SYNCARTICLESDIR"
			LOCALDIRECTORY="$LOCALARTICLESDIR"
			;;
		"--videos")
			SYNCDIRECTORY="$SYNCVIDEOSDIR"
			LOCALDIRECTORY="$LOCALVIDEOSDIR"
			;;
	esac
	cd "$LOCALDIRECTORY"
	if [ ! "$(ls)" = "" ] ; then
		for DIR in * ; do
			J=0
			cd "$SYNCDIRECTORY"
			if [ ! "$(ls)" = "" ] ; then
				for FILE in * ; do
					if [ "$DIR" = "$FILE" ] ; then
						J=1
					fi
				done
			fi
			if [ $J -eq 0 ] ; then
			echo Remove "$DIR"
			rm -r "$LOCALDIRECTORY"/"$DIR"
		fi
	done
	fi
}

download_all () {
	download --articles
	download --videos
}

clean_all () {
	clean --articles
	clean --videos
}

update () {
	clean_all
	download_all
}

usage () {
	cat << EOF
Use: $(basename $0) [option]
Options:   -h, --help              Display help
           -l, --list              List saved articles
           -u, --update            Update local copy
           -f, --force             Force re-download of an article
           -F, --force-all         Force re-download of all articles
           -a, --add url [url2…]   Add url(s)
           -o, --open              Open an article
           -r, --remove            Remove an article
           -R, --remove-all        Remove all articles
EOF
}

if [ $# -eq 0 ] ; then
	echo Error: missing argument
	usage
	exit 0
fi

if [ ! "$1" = "-a" ] && [ ! "$1" = "--add" ] && [ $# -ge 2 ] ; then
	echo Error: to many arguments
	usage
	exit 0
fi

case "$1" in
	"--help"|"-h")
		usage
		exit 0
		;;
	"--list"|"-l")
		list
		;;
	"--add"|"-a")
		if [ $# -eq 1 ] ; then
			echo Error: missing argument
			usage
			exit 0
		fi
		while test $# -ne 1 ; do
			shift
			add --article "$1"
		done
		update
		;;
	"--remove"|"-r")
		remove --article --articlesdir
		clean
		;;
	"--remove-all"|"-R")
		remove_dir "SYNCARTICLESDIR"
		clean
		;;
	"--force"|"-f")
		remove --article --storedir
		download --articles
		;;
	"--force-all"|"-F")
		remove_dir "$LOCALARTICLESDIR"
		download --articles
		;;
	"--open"|"-o")
		open --article
		;;
	"--update"|"-u")
		update
		;;
	*)
		echo Error: $1 invalid argument
		usage
		exit 0
		;;
esac

