#!/bin/bash

CONFIGFILE="/home/$USER/.config/ril/ril.conf"

if [ ! -f "$CONFIGFILE" ] ; then
	mkdir -p "$(dirname "$CONFIGFILE")"
	echo 'ARTICLESDIR="/home/$USER/Articles/"'  >> "$CONFIGFILE"
	echo 'STOREDIR="/home/$USER/.ReadItLater/"' >> "$CONFIGFILE"
	echo 'BROWSERCOMMAND=firefox'               >> "$CONFIGFILE"
	echo '#BROWSERCOMMAND=chromium-browser'     >> "$CONFIGFILE"
	echo Config file $CONFIGFILE created.
	echo You can now edit it to change variables.
	echo See README.md for more informations about variables.
	exit 0
fi

. "$CONFIGFILE"

if [ ! -d "$ARTICLESDIR" ] ; then
	mkdir "$ARTICLESDIR"
fi

if [ ! -d "$STOREDIR" ] ; then
	mkdir "$STOREDIR"
fi

add () {
	cd "$ARTICLESDIR"
	FILENAME=$(echo "$1" | sed "s/\/\//%/g" | cut -d% -f2 | sed "s/\//__/g")
	echo "$1" > "$FILENAME"
}

open () {
	cd "$STOREDIR"
	K=1
	for I in $(ls -tr) ; do
		I="$(echo "$I" | sed "s/__/\//g")"
		echo "$K" \| "$I"
		K=$(( $K+1 ))
	done

	echo Enter the number of the article you want to read:
	read NUMBER

	K=1
	for I in $(ls -tr) ; do
		if [ "$K" -eq "$NUMBER" ] ; then
			cd "$I"
			if [ ! "$(ls | grep html$)" = "" ] ; then
				$BROWSERCOMMAND *.html
			fi
			if [ ! "$(ls | grep htm$)" = "" ] ; then
				$BROWSERCOMMAND *.htm
			fi
			cd ..
		fi
		K=$(( $K+1 ))
	done
}

remove () {
	cd "$ARTICLESDIR"
	if [ ! "$(ls)" = "" ] ; then
		K=1
		for ARTICLE in $(ls -tr) ; do
			echo "$K" \| $(cat "$ARTICLE")
			K=$(( $K+1 ))
		done
		case "$1" in
			"--artcilesdir")
				echo "Enter the number(s) of the article(s) you want to remove (ex: 1 2 4):"
				;;
			"--storedir")
				echo "Enter the number(s) of the article(s) you want to re-download (ex: 1 2 4):"
				;;
		esac

		read NUMBER

		K=1
		for ARTICLE in $(ls -tr) ; do
			if [ "$(grep " $K " <<< " $NUMBER " )" ] ; then
				case "$1" in
					"--articlesdir")
						rm "$ARTICLE"
						;;
					"--storedir")
						cd "$STOREDIR"
						rm -r "$ARTICLE"
						;;
				esac
			fi
			K=$(( $K+1 ))
		done
	else
		echo No article saved
	fi
}

remove_storedir () {
	cd "$STOREDIR"
	rm -r *
}

remove_articlesdir () {
	cd "$ARTICLESDIR"
	rm *
}

list () {
	cd "$ARTICLESDIR"
	if [ ! "$(ls)" = "" ] ; then
		for ARTICLE in $(ls -tr) ; do
			cat "$ARTICLE"
		done
	else
		echo No article saved
	fi
}

download () {
	cd "$ARTICLESDIR"
	if [ ! "$(ls)" = "" ] ; then
		for FILE in * ; do
			cd "$STOREDIR"
			if [ ! -d "$FILE" ] ; then
				mkdir "$FILE"
				LINK="$(cat "$ARTICLESDIR"/"$FILE")"
				echo Download "$LINK"
				wget -nd -E -H -K -k -p -q -P "$FILE" "$LINK"
			fi
		done
	fi
}

clean () {
	cd "$STOREDIR"
	if [ ! "$(ls)" = "" ] ; then
		for DIR in * ; do
			J=0
			cd "$ARTICLESDIR"
			if [ ! "$(ls)" = "" ] ; then
				for FILE in * ; do
					if [ "$DIR" = "$FILE" ] ; then
						J=1
					fi
				done
			fi
			if [ $J -eq 0 ] ; then
			echo Remove "$DIR"
			rm -r "$STOREDIR"/"$DIR"
		fi
	done
	fi
}

update () {
	clean
	download
}

usage () {
	cat << EOF
Use: $(basename $0) [option]
Options:   -h, --help              Display help
           -l, --list              List saved articles
           -u, --update            Update local copy
           -f, --force             Force re-download of an article
           -F, --force-all         Force re-download of all articles
           -a, --add url [url2…]   Add url(s)
           -o, --open              Open an article
           -r, --remove            Remove an article
           -R, --remove-all        Remove all articles
EOF
}

if [ $# -eq 0 ] ; then
	echo Error: missing argument
	usage
	exit 0
fi

if [ ! "$1" = "-a" ] && [ ! "$1" = "--add" ] && [ $# -ge 2 ] ; then
	echo Error: to many arguments
	usage
	exit 0
fi

case "$1" in
	"--help"|"-h")
		usage
		exit 0
		;;
	"--list"|"-l")
		list
		;;
	"--add"|"-a")
		if [ $# -eq 1 ] ; then
			echo Error: missing argument
			usage
			exit 0
		fi
		while test $# -ne 1 ; do
			shift
			add "$1"
		done
		update
		;;
	"--remove"|"-r")
		remove --articlesdir
		clean
		;;
	"--remove-all"|"-R")
		remove_articlesdir
		clean
		;;
	"--force"|"-f")
		remove --storedir
		download
		;;
	"--force-all"|"-F")
		remove_storedir
		download
		;;
	"--open"|"-o")
		open
		;;
	"--update"|"-u")
		update
		;;
	*)
		echo Error: $1 invalid argument
		usage
		exit 0
		;;
esac

